[General]
key_pmi=3325188107
key_pmi_invite_msg="19126062_Hu\x1ef3nh Quang Th\x1eafng 19126062@student.hcmus.edu.vn is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: 19126062_Hu\x1ef3nh Quang Th\x1eafng 19126062@student.hcmus.edu.vn's Personal Meeting Room\r\n\r\nJoin Zoom Meeting\r\nhttps://zoom.us/j/3325188107?pwd=QTZiWm1STlFlMVh3SDRsbEdkRzk5dz09\r\n\r\nMeeting ID: 332 518 8107\r\nPasscode: FMc8Mc\r\n\r\n"
