# include ./themes/Harper.conf
# include ./themes/Tomorrow_Night_Eighties.conf
# include ./themes/Monokai_Classic.conf
# include ./themes/gruvbox_dark.conf
include ./themes/IC_Orange_PPL.conf
# this file config for kitty emulator
mouse_hide_wait 0
# font_family      auto
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size 15.0
map shift+alt+k scroll_line_up
map shift+alt+j scroll_line_down
map shift+alt+page_up scroll_page_up
map shift+alt+page_down scroll_page_down
map shift+alt+\ scroll_home
map shift+alt+/ scroll_end
allow_remote_control yes
