[Finder]
MemTest=false
SortColumn=0
SortOrder=0

[Global]
AgreeEULA=true
Compat=true
UILanguage=def
blRunMFP=true
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xac\0\0\0\x5\0\0\x3R\0\0\x3\xe1\0\0\x1\xae\0\0\0\a\0\0\x3P\0\0\x3\xdf\0\0\0\x1\0\0\0\0\x5\0\0\0\x1\xae\0\0\0\a\0\0\x3P\0\0\x3\xdf)
