// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1730164093);
user_pref("browser.search.region", "VN");
user_pref("calendar.caldav.googleResync", 1730164092);
user_pref("calendar.list.sortOrder", "0fb40143-b99f-4c2e-abd7-ae425d329cb6");
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.calendar-main-default", true);
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.calendar-main-in-composite", true);
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.disabled", true);
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.name", "Home");
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.type", "storage");
user_pref("calendar.registry.0fb40143-b99f-4c2e-abd7-ae425d329cb6.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Ho_Chi_Minh");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1730164102620");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250107005646");
user_pref("extensions.lastAppVersion", "128.6.0");
user_pref("extensions.lastPlatformVersion", "128.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1bef125b-98e1-4d5d-8e13-dc83026708c5\",\"google@search.mozilla.org\":\"73e490da-6a2f-4e98-8a79-0cd6ec59ace9\",\"ddg@search.mozilla.org\":\"36c7e371-6fe4-4f9b-b281-28d2f913dcc3\",\"amazondotcom@search.mozilla.org\":\"5369be32-4ac4-4bd7-9cc8-e1d174a34c78\",\"wikipedia@search.mozilla.org\":\"575bc781-7a3e-4f99-8ed1-e29062c9d394\",\"bing@search.mozilla.org\":\"c256fcd4-c5d1-4154-8a18-df1a51fcf74a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.displayname.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mailnews.database.global.datastore.id", "3fd8b27b-334e-4d2e-836e-a38ac864b01");
user_pref("mailnews.default_news_sort_order", 1);
user_pref("mailnews.default_sort_order", 1);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.16.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("toolkit.startup.last_success", 1737692114);
user_pref("toolkit.telemetry.cachedClientID", "df333850-ef5b-432a-8218-0b883b41e229");
user_pref("toolkit.telemetry.previousBuildID", "20250107005646");
