;; Application Launcher Module
[module/launcher]
type = custom/text

content = rofi
content-background = black
content-foreground = green

click-left = ~/.config/rofi/launchers/type-1/launcher.sh
click-right = launcher_t1

